### PR TITLE
Add copy of license to docs

### PR DESCRIPTION
**Pull request by thisac**
The SDK docs are failing (presumably) due to there being no license file in the docs folder.

* Add a copy of the license file to the docs folder.

### CODE REVIEW

**Comment by arcondello** [comment]
Why not a symbolic link?

**Comment by thisac** [comment]
I had that previously, but then it doesn't build locally on non-Unix systems. Not a huge issue, but this seems to be the solution in other packages so I went with this instead.

**Comment by arcondello** [comment]
> I had that previously

It looks like you were just using a relative link in the .rst file, rather than having a symbolic link to the LICENSE (like say in the [cloud client](https://github.com/dwavesystems/dwave-cloud-client/blob/master/docs/LICENSE))

**Review by arcondello — APPROVED** [review]

**Comment by thisac** [comment]
Oh, I mean previously as in when adding the docs to dwave-gate. Both the readme and license files were symbolic links, but didn't build correctly on Windows. Maybe this was just an issue with the readme though.

**Comment by randomir** [comment]
For the record, git handles symbolic links, and so they work on all platforms `git` works on.

**Pull request merged**
